export const es = {
    emptyMessage: 'No hay registros disponibles',
    loadingMessage: 'Cargando...',
    firstPageLabel: 'Primera página',
    previousPageLabel: 'Página anterior',
    nextPageLabel: 'Página siguiente',
    lastPageLabel: 'Última página',
    rowsPerPageLabel: 'Registros por página',
    currentPageReport: 'Mostrando {first} a {last} de {totalRecords} entradas',
    exportCsv: 'Exportar a CSV',
    exportExcel: 'Exportar a Excel',
    exportPdf: 'Exportar a PDF',
    filterPlaceholder: 'Buscar',
    filterMatchMode: 'Modo de coincidencia',
    filterExact: 'Exacto',
    filterContains: 'Contiene',
    filterLayout: 'Diseño de filtro',
    filterMatchModes: 'Modos de coincidencia',
    filterLocale: 'Configuración regional',
    filterAdvanced: 'Filtro avanzado',
    filterAddRule: 'Agregar regla',
    filterRemoveRule: 'Eliminar regla',
    filterAdvancedSearch: 'Búsqueda avanzada',
    filterAddGroup: 'Agregar grupo',
    filterRemoveGroup: 'Eliminar grupo',
    filterAndOperator: 'Y',
    filterOrOperator: 'O',
    filterStringOperator: 'Igual',
    filterNumberOperator: 'Igual',
    filterDateOperator: 'Igual',
    exportAll: 'Exportar todo',
    exportSelected: 'Exportar seleccionado',
    emptyFilterMessage: 'No hay resultados'
};
